--projects
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Red Wagon", "art", 25000, 2017-12-15, 2018-1-15);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();

--users
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();

--pledges
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
INSERT INTO pledge (amount, user_id, project_id) VALUES ();
